### ISSUE TITLE
请问可以直接用于 Tengine 上面麽？

### ISSUE THREAD

**Issue by eduosi** [xsec-lab/x-waf#2]
请问可以直接用于 Tengine 上面麽？

**Comment by netxfly** [comment]
刚看到，Tenine上面可以直接用。只要支持lua就行了，没有其他第三方模块。

**Comment by eduosi** [comment]
还有个建议，规则我看了一下源码，是区分大小写。这么就存在一个问题，我一个规则是 drop table ，如果区分大小写，得写很多规则。
还有两个个问题，问题一：黑名单、白名单 IP 那里 我全部删除后，去同步 rules 文件里面还有。问题二：测试发现 ip 规则匹配那里有 bug，黑名单ip里面有一个 1.1.1.1 ，用户的IP：27.14.101.161 竟然匹配成功了，然后就出现 403.

**Comment by BackTrackCRoot** [comment]
对于 IP匹配 我们的分支已经修复了匹配 还支撑 192.168.0.0/24 这样的区间匹配了。

**Comment by netxfly** [comment]
多谢宝贵的建议，现在已经解决了。
