### ISSUE TITLE
 lua entry thread aborted: runtime error:

### ISSUE THREAD

**Issue by leilianjie** [xsec-lab/x-waf#5]
rror] 16083#0: *1954 lua entry thread aborted: runtime error: /etc/nginx/x-waf/waf.lua:240: bad argument #1 to 'rulematch' (string expected, got boolean)

stack traceback:
coroutine 0:
	[C]: in function 'rulematch'
	/etc/nginx/x-waf/waf.lua:240: in function 'post_attack_check'
	/etc/nginx/x-waf/waf.lua:272: in function 'check'
	/etc/nginx/x-waf/access.lua:23: in function </etc/nginx/x-waf/access.lua:1>,

**Comment by netxfly** [comment]
已经修复。
