### ISSUE TITLE
waf没有正常工作

### ISSUE THREAD

**Issue by py0ker** [xsec-lab/x-waf#6]
请问一下，按照教程进行配置后，sudo /usr/local/openresty/nginx/sbin/nginx -t命令提示成功，没有报错。之后启动waf，sudo /usr/local/openresty/nginx/sbin/nginx，没有报错也没有任何提示信息。
之后在当前终端输入curl http://127.0.0.1/\?id\=1%20union%20select%201,2,3  返回信息没有关于“白帽子”的相关文字，只有正常的127.0.0.1访问页面的信息。想麻烦问一下有什么解决办法吗？

**Comment by netxfly** [comment]
在openresty中打开debug log后，看看有没有相关的输出。

**Comment by py0ker** [comment]
不好意思啊，我查看了相关log文件，在access.log中有访问记录，error.log也没有相关错误，可以麻烦您如果有时间可以加一下我的qq（516504745）指导一下吗？不胜感激

**Comment by netxfly** [comment]
debug log打开的指令是在nginx的errlog 指令近后面加debug，真打开的话，应该会有lua的日志信息输出。

**Comment by py0ker** [comment]
嗯嗯，好的，我再试一下，谢谢您
