### ISSUE TITLE
./configure error

### ISSUE THREAD

**Issue by wmltyq** [xsec-lab/x-waf#9]
Error detail info:
./configure: error: SSL modules require the OpenSSL library.
You can either do not enable the modules, or install the OpenSSL library
into the system, or build the OpenSSL library statically from the source
with nginx by using --with-openssl=<path> option.

ERROR: failed to run command: sh ./configure --prefix=/usr/local/openresty/nginx \...

How do I solve this?

**Comment by netxfly** [comment]
ubuntu:
```
sudo apt-get install libssl-dev
```

centos:
```
yum -y install openssl openssl-devel
```
